source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GLCKeychainWrapper_Example', :exclusive => true do
  pod "GLCKeychainWrapper", :path => "../"
end

target 'GLCKeychainWrapper_Tests', :exclusive => true do
  pod "GLCKeychainWrapper", :path => "../"

  
end
